###
GET http://localhost:5000/api/books 

###
GET http://localhost:5000/api/books/3


###
POST http://localhost:5000/api/books
Content-Type: application/json

{
  "Title": "Test",
  "Author" : "Test Author"
}

###
POST http://localhost:5000/api/books
Content-Type: application/json

{
  "Title": "Harry Potter", 
  "Author": "J. K. Rowling"
}

###
POST http://localhost:5000/api/books
Content-Type: application/json

{
  "Title": "The Lord of the Rings", 
  "Author": "J. R. R. Tolkien"
}

###
POST http://localhost:5000/api/books
Content-Type: application/json

{
  "Title": "The Wizard of Oz", 
  "Author": "L. Frank Baum"
}

###
PUT http://localhost:5000/api/books/5
Content-Type: application/json

{
  "Title":"update title",
  "Author": "Arigato"
}

###
DELETE http://localhost:5000/api/books/4
