###
GET http://localhost:5000/api/todos 

###
GET http://localhost:5000/api/todos/3


###
POST http://localhost:5000/api/todos
Content-Type: application/json

{
  "Text": "TEST", 
  "Day": "TEST", 
  "Reminder": "TRUE", 
}

###
POST http://localhost:5000/api/todos
Content-Type: application/json

{
  "Text": "Harry Potter", 
  "Day": "26/6/2565", 
  "Reminder": "FALSE", 
}


###
DELETE http://localhost:5000/api/todos/4


###
GET http://localhost:5000/api/books 

###
GET http://localhost:5000/api/books/3


###
POST http://localhost:5000/api/books
Content-Type: application/json

{
  "Title": "Test",
  "Author" : "Test Author"
}

###
POST http://localhost:5000/api/books
Content-Type: application/json

{
  "Title": "Harry Potter", 
  "Author": "J. K. Rowling"
}

###
POST http://localhost:5000/api/books
Content-Type: application/json

{
  "Title": "The Lord of the Rings", 
  "Author": "J. R. R. Tolkien"
}

###
POST http://localhost:5000/api/books
Content-Type: application/json

{
  "Title": "The Wizard of Oz", 
  "Author": "L. Frank Baum"
}

###
PUT http://localhost:5000/api/books/5
Content-Type: application/json

{
  "Title":"update title",
  "Author": "Arigato"
}

###
DELETE http://localhost:5000/api/books/4
