###
GET http://localhost:5000/books 

###
GET http://localhost:5000/books/3


###
POST http://localhost:5000/books
Content-Type: application/json

{
  "ID": "5",
  "Title": "Test",
  "Author" : "Test Author"
}

###
POST http://localhost:5000/books
Content-Type: application/json

{
  "ID": "1", 
  "Title": "Harry Potter", 
  "Author": "J. K. Rowling"
}

###
POST http://localhost:5000/books
Content-Type: application/json

{
  "ID": "2", 
  "Title": "The Lord of the Rings", 
  "Author": "J. R. R. Tolkien"
}

###
POST http://localhost:5000/books
Content-Type: application/json

{
  "ID": "3", 
  "Title": "The Wizard of Oz", 
  "Author": "L. Frank Baum"
}

###
PUT http://localhost:5000/books/5
Content-Type: application/json

{
  "Title":"update title",
  "Author": "Arigato"
}

###
DELETE http://localhost:5000/books/5
